chore: add terraform files to aws folder + add s3 shared state

diff --git a/.github/workflows/aws/create-infra-aws.yml b/.github/workflows/aws/create-infra-aws.yml
--- a/.github/workflows/aws/create-infra-aws.yml
+++ b/.github/workflows/aws/create-infra-aws.yml
@@ -22,6 +22,22 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v2
 
+      - name: Install AWS CLI
+        id: check_aws_cli
+        run: |
+          if ! command -v aws &> /dev/null; then
+            echo "AWS CLI not found, installing..."
+            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
+            unzip awscliv2.zip
+            sudo ./aws/install --update
+          else
+            echo "AWS CLI is already installed"
+          fi
+
+      - name: Create S3 Bucket
+        run: |
+          aws s3api create-bucket --bucket ${{ secrets.AWS_BUCKET_NAME }} --region ${{ secrets.AWS_REGION }} --create-bucket-configuration LocationConstraint=${{ secrets.AWS_REGION }}
+
       - name: Setup Terraform
         uses: hashicorp/setup-terraform@v1
 
@@ -38,7 +54,8 @@ jobs:
           -var="aws_access_key=${{ secrets.AWS_ACCESS_KEY_ID }}" \
           -var="aws_secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" \
           -var="aws_session_token=${{ secrets.AWS_SESSION_TOKEN }}" \
-          -var="aws_region=${{ secrets.AWS_REGION }}"
+          -var="aws_region=${{ secrets.AWS_REGION }}" \
+          -var="aws_bucket_name=${{ secrets.AWS_BUCKET_NAME }}"
 
       - name: Terraform Apply
         run: |
@@ -47,7 +64,8 @@ jobs:
           -var="aws_access_key=${{ secrets.AWS_ACCESS_KEY_ID }}" \
           -var="aws_secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" \
           -var="aws_session_token=${{ secrets.AWS_SESSION_TOKEN }}" \
-          -var="aws_region=${{ secrets.AWS_REGION }}"
+          -var="aws_region=${{ secrets.AWS_REGION }}" \
+          -var="aws_bucket_name=${{ secrets.AWS_BUCKET_NAME }}"
 
       - name: Terraform Output
         id: output
